version: '3.3'

services:
  postgresql:
    image: bitnami/postgresql:17.0.0
    container_name: postgresql
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password
    volumes:
      - ./psql:/bitnami/postgresql
    ports:
      - 5432:5432
    networks:
      - main-tier

networks:
  main-tier:
    driver: bridge