// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	usecase "kolresource/internal/admin/usecase"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAdminUseCase is a mock of AdminUseCase interface.
type MockAdminUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUseCaseMockRecorder
}

// MockAdminUseCaseMockRecorder is the mock recorder for MockAdminUseCase.
type MockAdminUseCaseMockRecorder struct {
	mock *MockAdminUseCase
}

// NewMockAdminUseCase creates a new mock instance.
func NewMockAdminUseCase(ctrl *gomock.Controller) *MockAdminUseCase {
	mock := &MockAdminUseCase{ctrl: ctrl}
	mock.recorder = &MockAdminUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUseCase) EXPECT() *MockAdminUseCaseMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAdminUseCase) Login(ctx context.Context, userName, password string) (*usecase.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, userName, password)
	ret0, _ := ret[0].(*usecase.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAdminUseCaseMockRecorder) Login(ctx, userName, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAdminUseCase)(nil).Login), ctx, userName, password)
}

// LoginTokenParser mocks base method.
func (m *MockAdminUseCase) LoginTokenParser(ctx context.Context, tokenString string) (*usecase.JWTAdminClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginTokenParser", ctx, tokenString)
	ret0, _ := ret[0].(*usecase.JWTAdminClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginTokenParser indicates an expected call of LoginTokenParser.
func (mr *MockAdminUseCaseMockRecorder) LoginTokenParser(ctx, tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginTokenParser", reflect.TypeOf((*MockAdminUseCase)(nil).LoginTokenParser), ctx, tokenString)
}

// Register mocks base method.
func (m *MockAdminUseCase) Register(ctx context.Context, param usecase.RegisterParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockAdminUseCaseMockRecorder) Register(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAdminUseCase)(nil).Register), ctx, param)
}
