// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go

// Package repositorymock is a generated GoMock package.
package repositorymock

import (
	context "context"
	email "kolresource/internal/email"
	domain "kolresource/internal/email/domain"
	entities "kolresource/internal/email/domain/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AllEmailSenders mocks base method.
func (m *MockRepository) AllEmailSenders(ctx context.Context) ([]*entities.EmailSender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllEmailSenders", ctx)
	ret0, _ := ret[0].([]*entities.EmailSender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllEmailSenders indicates an expected call of AllEmailSenders.
func (mr *MockRepositoryMockRecorder) AllEmailSenders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllEmailSenders", reflect.TypeOf((*MockRepository)(nil).AllEmailSenders), ctx)
}

// BatchCreateEmailLogs mocks base method.
func (m *MockRepository) BatchCreateEmailLogs(ctx context.Context, logs []*entities.EmailLog) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateEmailLogs", ctx, logs)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreateEmailLogs indicates an expected call of BatchCreateEmailLogs.
func (mr *MockRepositoryMockRecorder) BatchCreateEmailLogs(ctx, logs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateEmailLogs", reflect.TypeOf((*MockRepository)(nil).BatchCreateEmailLogs), ctx, logs)
}

// CountEmailLogsByJobIDAndStatus mocks base method.
func (m *MockRepository) CountEmailLogsByJobIDAndStatus(ctx context.Context, jobID int64, status email.LogStatus) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmailLogsByJobIDAndStatus", ctx, jobID, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmailLogsByJobIDAndStatus indicates an expected call of CountEmailLogsByJobIDAndStatus.
func (mr *MockRepositoryMockRecorder) CountEmailLogsByJobIDAndStatus(ctx, jobID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmailLogsByJobIDAndStatus", reflect.TypeOf((*MockRepository)(nil).CountEmailLogsByJobIDAndStatus), ctx, jobID, status)
}

// CountSentEmailsLast24Hours mocks base method.
func (m *MockRepository) CountSentEmailsLast24Hours(ctx context.Context, senderID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSentEmailsLast24Hours", ctx, senderID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSentEmailsLast24Hours indicates an expected call of CountSentEmailsLast24Hours.
func (mr *MockRepositoryMockRecorder) CountSentEmailsLast24Hours(ctx, senderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSentEmailsLast24Hours", reflect.TypeOf((*MockRepository)(nil).CountSentEmailsLast24Hours), ctx, senderID)
}

// CreateEmailJob mocks base method.
func (m *MockRepository) CreateEmailJob(ctx context.Context, job *entities.EmailJob) (*entities.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailJob", ctx, job)
	ret0, _ := ret[0].(*entities.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmailJob indicates an expected call of CreateEmailJob.
func (mr *MockRepositoryMockRecorder) CreateEmailJob(ctx, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailJob", reflect.TypeOf((*MockRepository)(nil).CreateEmailJob), ctx, job)
}

// CreateEmailSender mocks base method.
func (m *MockRepository) CreateEmailSender(ctx context.Context, sender *entities.EmailSender) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailSender", ctx, sender)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEmailSender indicates an expected call of CreateEmailSender.
func (mr *MockRepositoryMockRecorder) CreateEmailSender(ctx, sender interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailSender", reflect.TypeOf((*MockRepository)(nil).CreateEmailSender), ctx, sender)
}

// GetEmailJobByID mocks base method.
func (m *MockRepository) GetEmailJobByID(ctx context.Context, id int64) (*entities.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailJobByID", ctx, id)
	ret0, _ := ret[0].(*entities.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailJobByID indicates an expected call of GetEmailJobByID.
func (mr *MockRepositoryMockRecorder) GetEmailJobByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailJobByID", reflect.TypeOf((*MockRepository)(nil).GetEmailJobByID), ctx, id)
}

// GetEmailJobByIDForUpdate mocks base method.
func (m *MockRepository) GetEmailJobByIDForUpdate(ctx context.Context, id int64) (*entities.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailJobByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(*entities.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailJobByIDForUpdate indicates an expected call of GetEmailJobByIDForUpdate.
func (mr *MockRepositoryMockRecorder) GetEmailJobByIDForUpdate(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailJobByIDForUpdate", reflect.TypeOf((*MockRepository)(nil).GetEmailJobByIDForUpdate), ctx, id)
}

// GetEmailLog mocks base method.
func (m *MockRepository) GetEmailLog(ctx context.Context, id int64) (*entities.EmailLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailLog", ctx, id)
	ret0, _ := ret[0].(*entities.EmailLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailLog indicates an expected call of GetEmailLog.
func (mr *MockRepositoryMockRecorder) GetEmailLog(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailLog", reflect.TypeOf((*MockRepository)(nil).GetEmailLog), ctx, id)
}

// GetEmailSenderByEmail mocks base method.
func (m *MockRepository) GetEmailSenderByEmail(ctx context.Context, email string) (*entities.EmailSender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailSenderByEmail", ctx, email)
	ret0, _ := ret[0].(*entities.EmailSender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailSenderByEmail indicates an expected call of GetEmailSenderByEmail.
func (mr *MockRepositoryMockRecorder) GetEmailSenderByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailSenderByEmail", reflect.TypeOf((*MockRepository)(nil).GetEmailSenderByEmail), ctx, email)
}

// GetEmailSenderByID mocks base method.
func (m *MockRepository) GetEmailSenderByID(ctx context.Context, id uuid.UUID) (*entities.EmailSender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailSenderByID", ctx, id)
	ret0, _ := ret[0].(*entities.EmailSender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailSenderByID indicates an expected call of GetEmailSenderByID.
func (mr *MockRepositoryMockRecorder) GetEmailSenderByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailSenderByID", reflect.TypeOf((*MockRepository)(nil).GetEmailSenderByID), ctx, id)
}

// GrabEmailJob mocks base method.
func (m *MockRepository) GrabEmailJob(ctx context.Context) ([]*entities.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrabEmailJob", ctx)
	ret0, _ := ret[0].([]*entities.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GrabEmailJob indicates an expected call of GrabEmailJob.
func (mr *MockRepositoryMockRecorder) GrabEmailJob(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrabEmailJob", reflect.TypeOf((*MockRepository)(nil).GrabEmailJob), ctx)
}

// GrabPendingEmailLogByJobID mocks base method.
func (m *MockRepository) GrabPendingEmailLogByJobID(ctx context.Context, jobID int64) (*entities.EmailLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrabPendingEmailLogByJobID", ctx, jobID)
	ret0, _ := ret[0].(*entities.EmailLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GrabPendingEmailLogByJobID indicates an expected call of GrabPendingEmailLogByJobID.
func (mr *MockRepositoryMockRecorder) GrabPendingEmailLogByJobID(ctx, jobID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrabPendingEmailLogByJobID", reflect.TypeOf((*MockRepository)(nil).GrabPendingEmailLogByJobID), ctx, jobID)
}

// ListEmailJobs mocks base method.
func (m *MockRepository) ListEmailJobs(ctx context.Context, params *domain.ListEmailJobsParams) ([]*entities.EmailJob, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmailJobs", ctx, params)
	ret0, _ := ret[0].([]*entities.EmailJob)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEmailJobs indicates an expected call of ListEmailJobs.
func (mr *MockRepositoryMockRecorder) ListEmailJobs(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmailJobs", reflect.TypeOf((*MockRepository)(nil).ListEmailJobs), ctx, params)
}

// ListEmailLogs mocks base method.
func (m *MockRepository) ListEmailLogs(ctx context.Context, params *domain.ListEmailLogsParams) ([]*entities.EmailLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmailLogs", ctx, params)
	ret0, _ := ret[0].([]*entities.EmailLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmailLogs indicates an expected call of ListEmailLogs.
func (mr *MockRepositoryMockRecorder) ListEmailLogs(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmailLogs", reflect.TypeOf((*MockRepository)(nil).ListEmailLogs), ctx, params)
}

// UpdateEmailJob mocks base method.
func (m *MockRepository) UpdateEmailJob(ctx context.Context, param domain.UpdateEmailJobParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailJob", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmailJob indicates an expected call of UpdateEmailJob.
func (mr *MockRepositoryMockRecorder) UpdateEmailJob(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailJob", reflect.TypeOf((*MockRepository)(nil).UpdateEmailJob), ctx, param)
}

// UpdateEmailJobStats mocks base method.
func (m *MockRepository) UpdateEmailJobStats(ctx context.Context, id int64, status email.JobStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailJobStats", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmailJobStats indicates an expected call of UpdateEmailJobStats.
func (mr *MockRepositoryMockRecorder) UpdateEmailJobStats(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailJobStats", reflect.TypeOf((*MockRepository)(nil).UpdateEmailJobStats), ctx, id, status)
}

// UpdateEmailLog mocks base method.
func (m *MockRepository) UpdateEmailLog(ctx context.Context, param domain.UpdateEmailLogParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailLog", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmailLog indicates an expected call of UpdateEmailLog.
func (mr *MockRepositoryMockRecorder) UpdateEmailLog(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailLog", reflect.TypeOf((*MockRepository)(nil).UpdateEmailLog), ctx, param)
}

// UpdateEmailSender mocks base method.
func (m *MockRepository) UpdateEmailSender(ctx context.Context, param domain.UpdateEmailSenderParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailSender", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmailSender indicates an expected call of UpdateEmailSender.
func (mr *MockRepositoryMockRecorder) UpdateEmailSender(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailSender", reflect.TypeOf((*MockRepository)(nil).UpdateEmailSender), ctx, param)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), ctx, fn)
}

// MockEmailRepository is a mock of EmailRepository interface.
type MockEmailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailRepositoryMockRecorder
}

// MockEmailRepositoryMockRecorder is the mock recorder for MockEmailRepository.
type MockEmailRepositoryMockRecorder struct {
	mock *MockEmailRepository
}

// NewMockEmailRepository creates a new mock instance.
func NewMockEmailRepository(ctrl *gomock.Controller) *MockEmailRepository {
	mock := &MockEmailRepository{ctrl: ctrl}
	mock.recorder = &MockEmailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailRepository) EXPECT() *MockEmailRepositoryMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailRepository) SendEmail(ctx context.Context, param domain.SendEmailParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailRepositoryMockRecorder) SendEmail(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailRepository)(nil).SendEmail), ctx, param)
}
