// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	usecase "kolresource/internal/email/usecase"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockEmailUseCase is a mock of EmailUseCase interface.
type MockEmailUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockEmailUseCaseMockRecorder
}

// MockEmailUseCaseMockRecorder is the mock recorder for MockEmailUseCase.
type MockEmailUseCaseMockRecorder struct {
	mock *MockEmailUseCase
}

// NewMockEmailUseCase creates a new mock instance.
func NewMockEmailUseCase(ctrl *gomock.Controller) *MockEmailUseCase {
	mock := &MockEmailUseCase{ctrl: ctrl}
	mock.recorder = &MockEmailUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailUseCase) EXPECT() *MockEmailUseCaseMockRecorder {
	return m.recorder
}

// CancelEmailJob mocks base method.
func (m *MockEmailUseCase) CancelEmailJob(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelEmailJob", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelEmailJob indicates an expected call of CancelEmailJob.
func (mr *MockEmailUseCaseMockRecorder) CancelEmailJob(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelEmailJob", reflect.TypeOf((*MockEmailUseCase)(nil).CancelEmailJob), ctx, id)
}

// CreateEmailSender mocks base method.
func (m *MockEmailUseCase) CreateEmailSender(ctx context.Context, param usecase.CreateEmailSenderParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailSender", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEmailSender indicates an expected call of CreateEmailSender.
func (mr *MockEmailUseCaseMockRecorder) CreateEmailSender(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailSender", reflect.TypeOf((*MockEmailUseCase)(nil).CreateEmailSender), ctx, param)
}

// GetEmailJob mocks base method.
func (m *MockEmailUseCase) GetEmailJob(ctx context.Context, id int64) (*usecase.EmailJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailJob", ctx, id)
	ret0, _ := ret[0].(*usecase.EmailJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailJob indicates an expected call of GetEmailJob.
func (mr *MockEmailUseCaseMockRecorder) GetEmailJob(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailJob", reflect.TypeOf((*MockEmailUseCase)(nil).GetEmailJob), ctx, id)
}

// GetEmailSender mocks base method.
func (m *MockEmailUseCase) GetEmailSender(ctx context.Context, id uuid.UUID) (*usecase.EmailSender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailSender", ctx, id)
	ret0, _ := ret[0].(*usecase.EmailSender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailSender indicates an expected call of GetEmailSender.
func (mr *MockEmailUseCaseMockRecorder) GetEmailSender(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailSender", reflect.TypeOf((*MockEmailUseCase)(nil).GetEmailSender), ctx, id)
}

// ListEmailJobs mocks base method.
func (m *MockEmailUseCase) ListEmailJobs(ctx context.Context, param usecase.ListEmailJobsParam) (*usecase.ListEmailJobsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmailJobs", ctx, param)
	ret0, _ := ret[0].(*usecase.ListEmailJobsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmailJobs indicates an expected call of ListEmailJobs.
func (mr *MockEmailUseCaseMockRecorder) ListEmailJobs(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmailJobs", reflect.TypeOf((*MockEmailUseCase)(nil).ListEmailJobs), ctx, param)
}

// ListEmailLogs mocks base method.
func (m *MockEmailUseCase) ListEmailLogs(ctx context.Context, param usecase.ListEmailLogsParam) ([]usecase.EmailLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmailLogs", ctx, param)
	ret0, _ := ret[0].([]usecase.EmailLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmailLogs indicates an expected call of ListEmailLogs.
func (mr *MockEmailUseCaseMockRecorder) ListEmailLogs(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmailLogs", reflect.TypeOf((*MockEmailUseCase)(nil).ListEmailLogs), ctx, param)
}

// ListEmailSenders mocks base method.
func (m *MockEmailUseCase) ListEmailSenders(ctx context.Context) ([]usecase.EmailSender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmailSenders", ctx)
	ret0, _ := ret[0].([]usecase.EmailSender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmailSenders indicates an expected call of ListEmailSenders.
func (mr *MockEmailUseCaseMockRecorder) ListEmailSenders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmailSenders", reflect.TypeOf((*MockEmailUseCase)(nil).ListEmailSenders), ctx)
}

// SendEmail mocks base method.
func (m *MockEmailUseCase) SendEmail(ctx context.Context, param usecase.SendEmailParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailUseCaseMockRecorder) SendEmail(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailUseCase)(nil).SendEmail), ctx, param)
}

// StartEmailJob mocks base method.
func (m *MockEmailUseCase) StartEmailJob(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartEmailJob", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartEmailJob indicates an expected call of StartEmailJob.
func (mr *MockEmailUseCaseMockRecorder) StartEmailJob(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartEmailJob", reflect.TypeOf((*MockEmailUseCase)(nil).StartEmailJob), ctx, id)
}

// UpdateEmailSender mocks base method.
func (m *MockEmailUseCase) UpdateEmailSender(ctx context.Context, param usecase.UpdateEmailSenderParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmailSender", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmailSender indicates an expected call of UpdateEmailSender.
func (mr *MockEmailUseCaseMockRecorder) UpdateEmailSender(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmailSender", reflect.TypeOf((*MockEmailUseCase)(nil).UpdateEmailSender), ctx, param)
}
