// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go

// Package usecasemock is a generated GoMock package.
package usecasemock

import (
	context "context"
	usecase "kolresource/internal/kol/usecase"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockKolUseCase is a mock of KolUseCase interface.
type MockKolUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockKolUseCaseMockRecorder
}

// MockKolUseCaseMockRecorder is the mock recorder for MockKolUseCase.
type MockKolUseCaseMockRecorder struct {
	mock *MockKolUseCase
}

// NewMockKolUseCase creates a new mock instance.
func NewMockKolUseCase(ctrl *gomock.Controller) *MockKolUseCase {
	mock := &MockKolUseCase{ctrl: ctrl}
	mock.recorder = &MockKolUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKolUseCase) EXPECT() *MockKolUseCaseMockRecorder {
	return m.recorder
}

// BatchCreateKolsByXlsx mocks base method.
func (m *MockKolUseCase) BatchCreateKolsByXlsx(ctx context.Context, param usecase.BatchCreateKolsByXlsxParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateKolsByXlsx", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreateKolsByXlsx indicates an expected call of BatchCreateKolsByXlsx.
func (mr *MockKolUseCaseMockRecorder) BatchCreateKolsByXlsx(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateKolsByXlsx", reflect.TypeOf((*MockKolUseCase)(nil).BatchCreateKolsByXlsx), ctx, param)
}

// CreateKol mocks base method.
func (m *MockKolUseCase) CreateKol(ctx context.Context, param usecase.CreateKolParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKol", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKol indicates an expected call of CreateKol.
func (mr *MockKolUseCaseMockRecorder) CreateKol(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKol", reflect.TypeOf((*MockKolUseCase)(nil).CreateKol), ctx, param)
}

// CreateProduct mocks base method.
func (m *MockKolUseCase) CreateProduct(ctx context.Context, param usecase.CreateProductParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockKolUseCaseMockRecorder) CreateProduct(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockKolUseCase)(nil).CreateProduct), ctx, param)
}

// CreateTag mocks base method.
func (m *MockKolUseCase) CreateTag(ctx context.Context, param usecase.CreateTagParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockKolUseCaseMockRecorder) CreateTag(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockKolUseCase)(nil).CreateTag), ctx, param)
}

// DeleteKolByID mocks base method.
func (m *MockKolUseCase) DeleteKolByID(ctx context.Context, kolID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKolByID", ctx, kolID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKolByID indicates an expected call of DeleteKolByID.
func (mr *MockKolUseCaseMockRecorder) DeleteKolByID(ctx, kolID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKolByID", reflect.TypeOf((*MockKolUseCase)(nil).DeleteKolByID), ctx, kolID)
}

// GetKolByID mocks base method.
func (m *MockKolUseCase) GetKolByID(ctx context.Context, kolID uuid.UUID) (*usecase.Kol, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKolByID", ctx, kolID)
	ret0, _ := ret[0].(*usecase.Kol)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKolByID indicates an expected call of GetKolByID.
func (mr *MockKolUseCaseMockRecorder) GetKolByID(ctx, kolID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKolByID", reflect.TypeOf((*MockKolUseCase)(nil).GetKolByID), ctx, kolID)
}

// GetProductByID mocks base method.
func (m *MockKolUseCase) GetProductByID(ctx context.Context, productID uuid.UUID) (*usecase.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, productID)
	ret0, _ := ret[0].(*usecase.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockKolUseCaseMockRecorder) GetProductByID(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockKolUseCase)(nil).GetProductByID), ctx, productID)
}

// ListKolEmailsByIDs mocks base method.
func (m *MockKolUseCase) ListKolEmailsByIDs(ctx context.Context, kolIDs []uuid.UUID) ([]*usecase.KolEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKolEmailsByIDs", ctx, kolIDs)
	ret0, _ := ret[0].([]*usecase.KolEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKolEmailsByIDs indicates an expected call of ListKolEmailsByIDs.
func (mr *MockKolUseCaseMockRecorder) ListKolEmailsByIDs(ctx, kolIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKolEmailsByIDs", reflect.TypeOf((*MockKolUseCase)(nil).ListKolEmailsByIDs), ctx, kolIDs)
}

// ListKols mocks base method.
func (m *MockKolUseCase) ListKols(ctx context.Context, param usecase.ListKolsParam) ([]*usecase.Kol, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKols", ctx, param)
	ret0, _ := ret[0].([]*usecase.Kol)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListKols indicates an expected call of ListKols.
func (mr *MockKolUseCaseMockRecorder) ListKols(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKols", reflect.TypeOf((*MockKolUseCase)(nil).ListKols), ctx, param)
}

// ListProductsByName mocks base method.
func (m *MockKolUseCase) ListProductsByName(ctx context.Context, name string) ([]*usecase.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductsByName", ctx, name)
	ret0, _ := ret[0].([]*usecase.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductsByName indicates an expected call of ListProductsByName.
func (mr *MockKolUseCaseMockRecorder) ListProductsByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductsByName", reflect.TypeOf((*MockKolUseCase)(nil).ListProductsByName), ctx, name)
}

// ListTagsByName mocks base method.
func (m *MockKolUseCase) ListTagsByName(ctx context.Context, name string) ([]*usecase.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsByName", ctx, name)
	ret0, _ := ret[0].([]*usecase.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsByName indicates an expected call of ListTagsByName.
func (mr *MockKolUseCaseMockRecorder) ListTagsByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsByName", reflect.TypeOf((*MockKolUseCase)(nil).ListTagsByName), ctx, name)
}

// UpdateKol mocks base method.
func (m *MockKolUseCase) UpdateKol(ctx context.Context, param usecase.UpdateKolParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKol", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKol indicates an expected call of UpdateKol.
func (mr *MockKolUseCaseMockRecorder) UpdateKol(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKol", reflect.TypeOf((*MockKolUseCase)(nil).UpdateKol), ctx, param)
}
