// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"strconv"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]interface{}

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("model: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

type EmailJobStatus string

// Enum values for EmailJobStatus
const (
	EmailJobStatusPending          EmailJobStatus = "pending"
	EmailJobStatusProcessing       EmailJobStatus = "processing"
	EmailJobStatusSuccess          EmailJobStatus = "success"
	EmailJobStatusPartiallySuccess EmailJobStatus = "partially_success"
	EmailJobStatusFailed           EmailJobStatus = "failed"
	EmailJobStatusCanceled         EmailJobStatus = "canceled"
)

func AllEmailJobStatus() []EmailJobStatus {
	return []EmailJobStatus{
		EmailJobStatusPending,
		EmailJobStatusProcessing,
		EmailJobStatusSuccess,
		EmailJobStatusPartiallySuccess,
		EmailJobStatusFailed,
		EmailJobStatusCanceled,
	}
}

func (e EmailJobStatus) IsValid() error {
	switch e {
	case EmailJobStatusPending, EmailJobStatusProcessing, EmailJobStatusSuccess, EmailJobStatusPartiallySuccess, EmailJobStatusFailed, EmailJobStatusCanceled:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e EmailJobStatus) String() string {
	return string(e)
}

func (e EmailJobStatus) Ordinal() int {
	switch e {
	case EmailJobStatusPending:
		return 0
	case EmailJobStatusProcessing:
		return 1
	case EmailJobStatusSuccess:
		return 2
	case EmailJobStatusPartiallySuccess:
		return 3
	case EmailJobStatusFailed:
		return 4
	case EmailJobStatusCanceled:
		return 5

	default:
		panic(errors.New("enum is not valid"))
	}
}

type EmailLogStatus string

// Enum values for EmailLogStatus
const (
	EmailLogStatusPending  EmailLogStatus = "pending"
	EmailLogStatusSuccess  EmailLogStatus = "success"
	EmailLogStatusFailed   EmailLogStatus = "failed"
	EmailLogStatusCanceled EmailLogStatus = "canceled"
)

func AllEmailLogStatus() []EmailLogStatus {
	return []EmailLogStatus{
		EmailLogStatusPending,
		EmailLogStatusSuccess,
		EmailLogStatusFailed,
		EmailLogStatusCanceled,
	}
}

func (e EmailLogStatus) IsValid() error {
	switch e {
	case EmailLogStatusPending, EmailLogStatusSuccess, EmailLogStatusFailed, EmailLogStatusCanceled:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e EmailLogStatus) String() string {
	return string(e)
}

func (e EmailLogStatus) Ordinal() int {
	switch e {
	case EmailLogStatusPending:
		return 0
	case EmailLogStatusSuccess:
		return 1
	case EmailLogStatusFailed:
		return 2
	case EmailLogStatusCanceled:
		return 3

	default:
		panic(errors.New("enum is not valid"))
	}
}

type Sex string

// Enum values for Sex
const (
	SexM Sex = "m"
	SexF Sex = "f"
)

func AllSex() []Sex {
	return []Sex{
		SexM,
		SexF,
	}
}

func (e Sex) IsValid() error {
	switch e {
	case SexM, SexF:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e Sex) String() string {
	return string(e)
}

func (e Sex) Ordinal() int {
	switch e {
	case SexM:
		return 0
	case SexF:
		return 1

	default:
		panic(errors.New("enum is not valid"))
	}
}
