// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Admin        string
	EmailJob     string
	EmailLog     string
	EmailSender  string
	Kol          string
	KolTag       string
	Product      string
	SendEmailLog string
	Tag          string
}{
	Admin:        "admin",
	EmailJob:     "email_job",
	EmailLog:     "email_log",
	EmailSender:  "email_sender",
	Kol:          "kol",
	KolTag:       "kol_tag",
	Product:      "product",
	SendEmailLog: "send_email_log",
	Tag:          "tag",
}
