// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Admin        string
	Kol          string
	KolTag       string
	Product      string
	SendEmailLog string
	Tag          string
}{
	Admin:        "admin",
	Kol:          "kol",
	KolTag:       "kol_tag",
	Product:      "product",
	SendEmailLog: "send_email_log",
	Tag:          "tag",
}
