// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EmailSender is an object representing the database table.
type EmailSender struct {
	ID         string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name       string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Email      string    `boil:"email" json:"email" toml:"email" yaml:"email"`
	Key        string    `boil:"key" json:"key" toml:"key" yaml:"key"`
	RateLimit  int       `boil:"rate_limit" json:"rate_limit" toml:"rate_limit" yaml:"rate_limit"`
	LastSendAt time.Time `boil:"last_send_at" json:"last_send_at" toml:"last_send_at" yaml:"last_send_at"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *emailSenderR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L emailSenderL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EmailSenderColumns = struct {
	ID         string
	Name       string
	Email      string
	Key        string
	RateLimit  string
	LastSendAt string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "id",
	Name:       "name",
	Email:      "email",
	Key:        "key",
	RateLimit:  "rate_limit",
	LastSendAt: "last_send_at",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

var EmailSenderTableColumns = struct {
	ID         string
	Name       string
	Email      string
	Key        string
	RateLimit  string
	LastSendAt string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "email_sender.id",
	Name:       "email_sender.name",
	Email:      "email_sender.email",
	Key:        "email_sender.key",
	RateLimit:  "email_sender.rate_limit",
	LastSendAt: "email_sender.last_send_at",
	CreatedAt:  "email_sender.created_at",
	UpdatedAt:  "email_sender.updated_at",
}

// Generated where

var EmailSenderWhere = struct {
	ID         whereHelperstring
	Name       whereHelperstring
	Email      whereHelperstring
	Key        whereHelperstring
	RateLimit  whereHelperint
	LastSendAt whereHelpertime_Time
	CreatedAt  whereHelpertime_Time
	UpdatedAt  whereHelpertime_Time
}{
	ID:         whereHelperstring{field: "\"email_sender\".\"id\""},
	Name:       whereHelperstring{field: "\"email_sender\".\"name\""},
	Email:      whereHelperstring{field: "\"email_sender\".\"email\""},
	Key:        whereHelperstring{field: "\"email_sender\".\"key\""},
	RateLimit:  whereHelperint{field: "\"email_sender\".\"rate_limit\""},
	LastSendAt: whereHelpertime_Time{field: "\"email_sender\".\"last_send_at\""},
	CreatedAt:  whereHelpertime_Time{field: "\"email_sender\".\"created_at\""},
	UpdatedAt:  whereHelpertime_Time{field: "\"email_sender\".\"updated_at\""},
}

// EmailSenderRels is where relationship names are stored.
var EmailSenderRels = struct {
}{}

// emailSenderR is where relationships are stored.
type emailSenderR struct {
}

// NewStruct creates a new relationship struct
func (*emailSenderR) NewStruct() *emailSenderR {
	return &emailSenderR{}
}

// emailSenderL is where Load methods for each relationship are stored.
type emailSenderL struct{}

var (
	emailSenderAllColumns            = []string{"id", "name", "email", "key", "rate_limit", "last_send_at", "created_at", "updated_at"}
	emailSenderColumnsWithoutDefault = []string{"name", "email", "key", "rate_limit", "last_send_at"}
	emailSenderColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	emailSenderPrimaryKeyColumns     = []string{"id"}
	emailSenderGeneratedColumns      = []string{}
)

type (
	// EmailSenderSlice is an alias for a slice of pointers to EmailSender.
	// This should almost always be used instead of []EmailSender.
	EmailSenderSlice []*EmailSender
	// EmailSenderHook is the signature for custom EmailSender hook methods
	EmailSenderHook func(context.Context, boil.ContextExecutor, *EmailSender) error

	emailSenderQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	emailSenderType                 = reflect.TypeOf(&EmailSender{})
	emailSenderMapping              = queries.MakeStructMapping(emailSenderType)
	emailSenderPrimaryKeyMapping, _ = queries.BindMapping(emailSenderType, emailSenderMapping, emailSenderPrimaryKeyColumns)
	emailSenderInsertCacheMut       sync.RWMutex
	emailSenderInsertCache          = make(map[string]insertCache)
	emailSenderUpdateCacheMut       sync.RWMutex
	emailSenderUpdateCache          = make(map[string]updateCache)
	emailSenderUpsertCacheMut       sync.RWMutex
	emailSenderUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var emailSenderAfterSelectMu sync.Mutex
var emailSenderAfterSelectHooks []EmailSenderHook

var emailSenderBeforeInsertMu sync.Mutex
var emailSenderBeforeInsertHooks []EmailSenderHook
var emailSenderAfterInsertMu sync.Mutex
var emailSenderAfterInsertHooks []EmailSenderHook

var emailSenderBeforeUpdateMu sync.Mutex
var emailSenderBeforeUpdateHooks []EmailSenderHook
var emailSenderAfterUpdateMu sync.Mutex
var emailSenderAfterUpdateHooks []EmailSenderHook

var emailSenderBeforeDeleteMu sync.Mutex
var emailSenderBeforeDeleteHooks []EmailSenderHook
var emailSenderAfterDeleteMu sync.Mutex
var emailSenderAfterDeleteHooks []EmailSenderHook

var emailSenderBeforeUpsertMu sync.Mutex
var emailSenderBeforeUpsertHooks []EmailSenderHook
var emailSenderAfterUpsertMu sync.Mutex
var emailSenderAfterUpsertHooks []EmailSenderHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EmailSender) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailSenderAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EmailSender) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailSenderBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EmailSender) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailSenderAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EmailSender) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailSenderBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EmailSender) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailSenderAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EmailSender) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailSenderBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EmailSender) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailSenderAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EmailSender) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailSenderBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EmailSender) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailSenderAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEmailSenderHook registers your hook function for all future operations.
func AddEmailSenderHook(hookPoint boil.HookPoint, emailSenderHook EmailSenderHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		emailSenderAfterSelectMu.Lock()
		emailSenderAfterSelectHooks = append(emailSenderAfterSelectHooks, emailSenderHook)
		emailSenderAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		emailSenderBeforeInsertMu.Lock()
		emailSenderBeforeInsertHooks = append(emailSenderBeforeInsertHooks, emailSenderHook)
		emailSenderBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		emailSenderAfterInsertMu.Lock()
		emailSenderAfterInsertHooks = append(emailSenderAfterInsertHooks, emailSenderHook)
		emailSenderAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		emailSenderBeforeUpdateMu.Lock()
		emailSenderBeforeUpdateHooks = append(emailSenderBeforeUpdateHooks, emailSenderHook)
		emailSenderBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		emailSenderAfterUpdateMu.Lock()
		emailSenderAfterUpdateHooks = append(emailSenderAfterUpdateHooks, emailSenderHook)
		emailSenderAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		emailSenderBeforeDeleteMu.Lock()
		emailSenderBeforeDeleteHooks = append(emailSenderBeforeDeleteHooks, emailSenderHook)
		emailSenderBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		emailSenderAfterDeleteMu.Lock()
		emailSenderAfterDeleteHooks = append(emailSenderAfterDeleteHooks, emailSenderHook)
		emailSenderAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		emailSenderBeforeUpsertMu.Lock()
		emailSenderBeforeUpsertHooks = append(emailSenderBeforeUpsertHooks, emailSenderHook)
		emailSenderBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		emailSenderAfterUpsertMu.Lock()
		emailSenderAfterUpsertHooks = append(emailSenderAfterUpsertHooks, emailSenderHook)
		emailSenderAfterUpsertMu.Unlock()
	}
}

// One returns a single emailSender record from the query.
func (q emailSenderQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EmailSender, error) {
	o := &EmailSender{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to execute a one query for email_sender")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EmailSender records from the query.
func (q emailSenderQuery) All(ctx context.Context, exec boil.ContextExecutor) (EmailSenderSlice, error) {
	var o []*EmailSender

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to EmailSender slice")
	}

	if len(emailSenderAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EmailSender records in the query.
func (q emailSenderQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count email_sender rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q emailSenderQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if email_sender exists")
	}

	return count > 0, nil
}

// EmailSenders retrieves all the records using an executor.
func EmailSenders(mods ...qm.QueryMod) emailSenderQuery {
	mods = append(mods, qm.From("\"email_sender\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"email_sender\".*"})
	}

	return emailSenderQuery{q}
}

// FindEmailSender retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEmailSender(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*EmailSender, error) {
	emailSenderObj := &EmailSender{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"email_sender\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, emailSenderObj)
	if err != nil {
		return nil, errors.Wrap(err, "model: unable to select from email_sender")
	}

	if err = emailSenderObj.doAfterSelectHooks(ctx, exec); err != nil {
		return emailSenderObj, err
	}

	return emailSenderObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EmailSender) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no email_sender provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailSenderColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	emailSenderInsertCacheMut.RLock()
	cache, cached := emailSenderInsertCache[key]
	emailSenderInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			emailSenderAllColumns,
			emailSenderColumnsWithDefault,
			emailSenderColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(emailSenderType, emailSenderMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(emailSenderType, emailSenderMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"email_sender\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"email_sender\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into email_sender")
	}

	if !cached {
		emailSenderInsertCacheMut.Lock()
		emailSenderInsertCache[key] = cache
		emailSenderInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EmailSender.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EmailSender) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	emailSenderUpdateCacheMut.RLock()
	cache, cached := emailSenderUpdateCache[key]
	emailSenderUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			emailSenderAllColumns,
			emailSenderPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("model: unable to update email_sender, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"email_sender\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, emailSenderPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(emailSenderType, emailSenderMapping, append(wl, emailSenderPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update email_sender row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by update for email_sender")
	}

	if !cached {
		emailSenderUpdateCacheMut.Lock()
		emailSenderUpdateCache[key] = cache
		emailSenderUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q emailSenderQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all for email_sender")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected for email_sender")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EmailSenderSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailSenderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"email_sender\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, emailSenderPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all in emailSender slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected all in update all emailSender")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EmailSender) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("model: no email_sender provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailSenderColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	emailSenderUpsertCacheMut.RLock()
	cache, cached := emailSenderUpsertCache[key]
	emailSenderUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			emailSenderAllColumns,
			emailSenderColumnsWithDefault,
			emailSenderColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			emailSenderAllColumns,
			emailSenderPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("model: unable to upsert email_sender, could not build update column list")
		}

		ret := strmangle.SetComplement(emailSenderAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(emailSenderPrimaryKeyColumns) == 0 {
				return errors.New("model: unable to upsert email_sender, could not build conflict column list")
			}

			conflict = make([]string, len(emailSenderPrimaryKeyColumns))
			copy(conflict, emailSenderPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"email_sender\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(emailSenderType, emailSenderMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(emailSenderType, emailSenderMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "model: unable to upsert email_sender")
	}

	if !cached {
		emailSenderUpsertCacheMut.Lock()
		emailSenderUpsertCache[key] = cache
		emailSenderUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EmailSender record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EmailSender) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no EmailSender provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), emailSenderPrimaryKeyMapping)
	sql := "DELETE FROM \"email_sender\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete from email_sender")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by delete for email_sender")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q emailSenderQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("model: no emailSenderQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from email_sender")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for email_sender")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EmailSenderSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(emailSenderBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailSenderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"email_sender\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailSenderPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from emailSender slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for email_sender")
	}

	if len(emailSenderAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EmailSender) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEmailSender(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EmailSenderSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EmailSenderSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailSenderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"email_sender\".* FROM \"email_sender\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailSenderPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in EmailSenderSlice")
	}

	*o = slice

	return nil
}

// EmailSenderExists checks if the EmailSender row exists.
func EmailSenderExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"email_sender\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if email_sender exists")
	}

	return exists, nil
}

// Exists checks if the EmailSender row exists.
func (o *EmailSender) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EmailSenderExists(ctx, exec, o.ID)
}
