// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// EmailJob is an object representing the database table.
type EmailJob struct {
	ID                   int64          `boil:"id" json:"id" toml:"id" yaml:"id"`
	ExpectedReciverCount int            `boil:"expected_reciver_count" json:"expected_reciver_count" toml:"expected_reciver_count" yaml:"expected_reciver_count"`
	SuccessCount         int            `boil:"success_count" json:"success_count" toml:"success_count" yaml:"success_count"`
	SenderID             string         `boil:"sender_id" json:"sender_id" toml:"sender_id" yaml:"sender_id"`
	SenderName           string         `boil:"sender_name" json:"sender_name" toml:"sender_name" yaml:"sender_name"`
	SenderEmail          string         `boil:"sender_email" json:"sender_email" toml:"sender_email" yaml:"sender_email"`
	AdminID              string         `boil:"admin_id" json:"admin_id" toml:"admin_id" yaml:"admin_id"`
	AdminName            string         `boil:"admin_name" json:"admin_name" toml:"admin_name" yaml:"admin_name"`
	ProductID            string         `boil:"product_id" json:"product_id" toml:"product_id" yaml:"product_id"`
	ProductName          string         `boil:"product_name" json:"product_name" toml:"product_name" yaml:"product_name"`
	Memo                 string         `boil:"memo" json:"memo" toml:"memo" yaml:"memo"`
	Payload              types.JSON     `boil:"payload" json:"payload" toml:"payload" yaml:"payload"`
	Status               EmailJobStatus `boil:"status" json:"status" toml:"status" yaml:"status"`
	CreatedAt            time.Time      `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt            time.Time      `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	LastExecuteAt        time.Time      `boil:"last_execute_at" json:"last_execute_at" toml:"last_execute_at" yaml:"last_execute_at"`

	R *emailJobR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L emailJobL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EmailJobColumns = struct {
	ID                   string
	ExpectedReciverCount string
	SuccessCount         string
	SenderID             string
	SenderName           string
	SenderEmail          string
	AdminID              string
	AdminName            string
	ProductID            string
	ProductName          string
	Memo                 string
	Payload              string
	Status               string
	CreatedAt            string
	UpdatedAt            string
	LastExecuteAt        string
}{
	ID:                   "id",
	ExpectedReciverCount: "expected_reciver_count",
	SuccessCount:         "success_count",
	SenderID:             "sender_id",
	SenderName:           "sender_name",
	SenderEmail:          "sender_email",
	AdminID:              "admin_id",
	AdminName:            "admin_name",
	ProductID:            "product_id",
	ProductName:          "product_name",
	Memo:                 "memo",
	Payload:              "payload",
	Status:               "status",
	CreatedAt:            "created_at",
	UpdatedAt:            "updated_at",
	LastExecuteAt:        "last_execute_at",
}

var EmailJobTableColumns = struct {
	ID                   string
	ExpectedReciverCount string
	SuccessCount         string
	SenderID             string
	SenderName           string
	SenderEmail          string
	AdminID              string
	AdminName            string
	ProductID            string
	ProductName          string
	Memo                 string
	Payload              string
	Status               string
	CreatedAt            string
	UpdatedAt            string
	LastExecuteAt        string
}{
	ID:                   "email_job.id",
	ExpectedReciverCount: "email_job.expected_reciver_count",
	SuccessCount:         "email_job.success_count",
	SenderID:             "email_job.sender_id",
	SenderName:           "email_job.sender_name",
	SenderEmail:          "email_job.sender_email",
	AdminID:              "email_job.admin_id",
	AdminName:            "email_job.admin_name",
	ProductID:            "email_job.product_id",
	ProductName:          "email_job.product_name",
	Memo:                 "email_job.memo",
	Payload:              "email_job.payload",
	Status:               "email_job.status",
	CreatedAt:            "email_job.created_at",
	UpdatedAt:            "email_job.updated_at",
	LastExecuteAt:        "email_job.last_execute_at",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelperEmailJobStatus struct{ field string }

func (w whereHelperEmailJobStatus) EQ(x EmailJobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperEmailJobStatus) NEQ(x EmailJobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperEmailJobStatus) LT(x EmailJobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperEmailJobStatus) LTE(x EmailJobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperEmailJobStatus) GT(x EmailJobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperEmailJobStatus) GTE(x EmailJobStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperEmailJobStatus) IN(slice []EmailJobStatus) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperEmailJobStatus) NIN(slice []EmailJobStatus) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var EmailJobWhere = struct {
	ID                   whereHelperint64
	ExpectedReciverCount whereHelperint
	SuccessCount         whereHelperint
	SenderID             whereHelperstring
	SenderName           whereHelperstring
	SenderEmail          whereHelperstring
	AdminID              whereHelperstring
	AdminName            whereHelperstring
	ProductID            whereHelperstring
	ProductName          whereHelperstring
	Memo                 whereHelperstring
	Payload              whereHelpertypes_JSON
	Status               whereHelperEmailJobStatus
	CreatedAt            whereHelpertime_Time
	UpdatedAt            whereHelpertime_Time
	LastExecuteAt        whereHelpertime_Time
}{
	ID:                   whereHelperint64{field: "\"email_job\".\"id\""},
	ExpectedReciverCount: whereHelperint{field: "\"email_job\".\"expected_reciver_count\""},
	SuccessCount:         whereHelperint{field: "\"email_job\".\"success_count\""},
	SenderID:             whereHelperstring{field: "\"email_job\".\"sender_id\""},
	SenderName:           whereHelperstring{field: "\"email_job\".\"sender_name\""},
	SenderEmail:          whereHelperstring{field: "\"email_job\".\"sender_email\""},
	AdminID:              whereHelperstring{field: "\"email_job\".\"admin_id\""},
	AdminName:            whereHelperstring{field: "\"email_job\".\"admin_name\""},
	ProductID:            whereHelperstring{field: "\"email_job\".\"product_id\""},
	ProductName:          whereHelperstring{field: "\"email_job\".\"product_name\""},
	Memo:                 whereHelperstring{field: "\"email_job\".\"memo\""},
	Payload:              whereHelpertypes_JSON{field: "\"email_job\".\"payload\""},
	Status:               whereHelperEmailJobStatus{field: "\"email_job\".\"status\""},
	CreatedAt:            whereHelpertime_Time{field: "\"email_job\".\"created_at\""},
	UpdatedAt:            whereHelpertime_Time{field: "\"email_job\".\"updated_at\""},
	LastExecuteAt:        whereHelpertime_Time{field: "\"email_job\".\"last_execute_at\""},
}

// EmailJobRels is where relationship names are stored.
var EmailJobRels = struct {
}{}

// emailJobR is where relationships are stored.
type emailJobR struct {
}

// NewStruct creates a new relationship struct
func (*emailJobR) NewStruct() *emailJobR {
	return &emailJobR{}
}

// emailJobL is where Load methods for each relationship are stored.
type emailJobL struct{}

var (
	emailJobAllColumns            = []string{"id", "expected_reciver_count", "success_count", "sender_id", "sender_name", "sender_email", "admin_id", "admin_name", "product_id", "product_name", "memo", "payload", "status", "created_at", "updated_at", "last_execute_at"}
	emailJobColumnsWithoutDefault = []string{"sender_id", "sender_name", "sender_email", "admin_id", "admin_name", "product_id", "product_name", "memo", "status"}
	emailJobColumnsWithDefault    = []string{"id", "expected_reciver_count", "success_count", "payload", "created_at", "updated_at", "last_execute_at"}
	emailJobPrimaryKeyColumns     = []string{"id"}
	emailJobGeneratedColumns      = []string{}
)

type (
	// EmailJobSlice is an alias for a slice of pointers to EmailJob.
	// This should almost always be used instead of []EmailJob.
	EmailJobSlice []*EmailJob
	// EmailJobHook is the signature for custom EmailJob hook methods
	EmailJobHook func(context.Context, boil.ContextExecutor, *EmailJob) error

	emailJobQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	emailJobType                 = reflect.TypeOf(&EmailJob{})
	emailJobMapping              = queries.MakeStructMapping(emailJobType)
	emailJobPrimaryKeyMapping, _ = queries.BindMapping(emailJobType, emailJobMapping, emailJobPrimaryKeyColumns)
	emailJobInsertCacheMut       sync.RWMutex
	emailJobInsertCache          = make(map[string]insertCache)
	emailJobUpdateCacheMut       sync.RWMutex
	emailJobUpdateCache          = make(map[string]updateCache)
	emailJobUpsertCacheMut       sync.RWMutex
	emailJobUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var emailJobAfterSelectMu sync.Mutex
var emailJobAfterSelectHooks []EmailJobHook

var emailJobBeforeInsertMu sync.Mutex
var emailJobBeforeInsertHooks []EmailJobHook
var emailJobAfterInsertMu sync.Mutex
var emailJobAfterInsertHooks []EmailJobHook

var emailJobBeforeUpdateMu sync.Mutex
var emailJobBeforeUpdateHooks []EmailJobHook
var emailJobAfterUpdateMu sync.Mutex
var emailJobAfterUpdateHooks []EmailJobHook

var emailJobBeforeDeleteMu sync.Mutex
var emailJobBeforeDeleteHooks []EmailJobHook
var emailJobAfterDeleteMu sync.Mutex
var emailJobAfterDeleteHooks []EmailJobHook

var emailJobBeforeUpsertMu sync.Mutex
var emailJobBeforeUpsertHooks []EmailJobHook
var emailJobAfterUpsertMu sync.Mutex
var emailJobAfterUpsertHooks []EmailJobHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EmailJob) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailJobAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EmailJob) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailJobBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EmailJob) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailJobAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EmailJob) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailJobBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EmailJob) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailJobAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EmailJob) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailJobBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EmailJob) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailJobAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EmailJob) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailJobBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EmailJob) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailJobAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEmailJobHook registers your hook function for all future operations.
func AddEmailJobHook(hookPoint boil.HookPoint, emailJobHook EmailJobHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		emailJobAfterSelectMu.Lock()
		emailJobAfterSelectHooks = append(emailJobAfterSelectHooks, emailJobHook)
		emailJobAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		emailJobBeforeInsertMu.Lock()
		emailJobBeforeInsertHooks = append(emailJobBeforeInsertHooks, emailJobHook)
		emailJobBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		emailJobAfterInsertMu.Lock()
		emailJobAfterInsertHooks = append(emailJobAfterInsertHooks, emailJobHook)
		emailJobAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		emailJobBeforeUpdateMu.Lock()
		emailJobBeforeUpdateHooks = append(emailJobBeforeUpdateHooks, emailJobHook)
		emailJobBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		emailJobAfterUpdateMu.Lock()
		emailJobAfterUpdateHooks = append(emailJobAfterUpdateHooks, emailJobHook)
		emailJobAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		emailJobBeforeDeleteMu.Lock()
		emailJobBeforeDeleteHooks = append(emailJobBeforeDeleteHooks, emailJobHook)
		emailJobBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		emailJobAfterDeleteMu.Lock()
		emailJobAfterDeleteHooks = append(emailJobAfterDeleteHooks, emailJobHook)
		emailJobAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		emailJobBeforeUpsertMu.Lock()
		emailJobBeforeUpsertHooks = append(emailJobBeforeUpsertHooks, emailJobHook)
		emailJobBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		emailJobAfterUpsertMu.Lock()
		emailJobAfterUpsertHooks = append(emailJobAfterUpsertHooks, emailJobHook)
		emailJobAfterUpsertMu.Unlock()
	}
}

// One returns a single emailJob record from the query.
func (q emailJobQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EmailJob, error) {
	o := &EmailJob{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to execute a one query for email_job")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EmailJob records from the query.
func (q emailJobQuery) All(ctx context.Context, exec boil.ContextExecutor) (EmailJobSlice, error) {
	var o []*EmailJob

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to EmailJob slice")
	}

	if len(emailJobAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EmailJob records in the query.
func (q emailJobQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count email_job rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q emailJobQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if email_job exists")
	}

	return count > 0, nil
}

// EmailJobs retrieves all the records using an executor.
func EmailJobs(mods ...qm.QueryMod) emailJobQuery {
	mods = append(mods, qm.From("\"email_job\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"email_job\".*"})
	}

	return emailJobQuery{q}
}

// FindEmailJob retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEmailJob(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*EmailJob, error) {
	emailJobObj := &EmailJob{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"email_job\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, emailJobObj)
	if err != nil {
		return nil, errors.Wrap(err, "model: unable to select from email_job")
	}

	if err = emailJobObj.doAfterSelectHooks(ctx, exec); err != nil {
		return emailJobObj, err
	}

	return emailJobObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EmailJob) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no email_job provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailJobColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	emailJobInsertCacheMut.RLock()
	cache, cached := emailJobInsertCache[key]
	emailJobInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			emailJobAllColumns,
			emailJobColumnsWithDefault,
			emailJobColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(emailJobType, emailJobMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(emailJobType, emailJobMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"email_job\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"email_job\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into email_job")
	}

	if !cached {
		emailJobInsertCacheMut.Lock()
		emailJobInsertCache[key] = cache
		emailJobInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EmailJob.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EmailJob) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	emailJobUpdateCacheMut.RLock()
	cache, cached := emailJobUpdateCache[key]
	emailJobUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			emailJobAllColumns,
			emailJobPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("model: unable to update email_job, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"email_job\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, emailJobPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(emailJobType, emailJobMapping, append(wl, emailJobPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update email_job row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by update for email_job")
	}

	if !cached {
		emailJobUpdateCacheMut.Lock()
		emailJobUpdateCache[key] = cache
		emailJobUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q emailJobQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all for email_job")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected for email_job")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EmailJobSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"email_job\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, emailJobPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all in emailJob slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected all in update all emailJob")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EmailJob) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("model: no email_job provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailJobColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	emailJobUpsertCacheMut.RLock()
	cache, cached := emailJobUpsertCache[key]
	emailJobUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			emailJobAllColumns,
			emailJobColumnsWithDefault,
			emailJobColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			emailJobAllColumns,
			emailJobPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("model: unable to upsert email_job, could not build update column list")
		}

		ret := strmangle.SetComplement(emailJobAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(emailJobPrimaryKeyColumns) == 0 {
				return errors.New("model: unable to upsert email_job, could not build conflict column list")
			}

			conflict = make([]string, len(emailJobPrimaryKeyColumns))
			copy(conflict, emailJobPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"email_job\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(emailJobType, emailJobMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(emailJobType, emailJobMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "model: unable to upsert email_job")
	}

	if !cached {
		emailJobUpsertCacheMut.Lock()
		emailJobUpsertCache[key] = cache
		emailJobUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EmailJob record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EmailJob) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no EmailJob provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), emailJobPrimaryKeyMapping)
	sql := "DELETE FROM \"email_job\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete from email_job")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by delete for email_job")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q emailJobQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("model: no emailJobQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from email_job")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for email_job")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EmailJobSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(emailJobBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"email_job\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailJobPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from emailJob slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for email_job")
	}

	if len(emailJobAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EmailJob) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEmailJob(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EmailJobSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EmailJobSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailJobPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"email_job\".* FROM \"email_job\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailJobPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in EmailJobSlice")
	}

	*o = slice

	return nil
}

// EmailJobExists checks if the EmailJob row exists.
func EmailJobExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"email_job\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if email_job exists")
	}

	return exists, nil
}

// Exists checks if the EmailJob row exists.
func (o *EmailJob) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EmailJobExists(ctx, exec, o.ID)
}
