// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// EmailLog is an object representing the database table.
type EmailLog struct {
	ID        int64          `boil:"id" json:"id" toml:"id" yaml:"id"`
	JobID     int64          `boil:"job_id" json:"job_id" toml:"job_id" yaml:"job_id"`
	ProductID string         `boil:"product_id" json:"product_id" toml:"product_id" yaml:"product_id"`
	SenderID  string         `boil:"sender_id" json:"sender_id" toml:"sender_id" yaml:"sender_id"`
	Email     string         `boil:"email" json:"email" toml:"email" yaml:"email"`
	MessageID string         `boil:"message_id" json:"message_id" toml:"message_id" yaml:"message_id"`
	Reply     bool           `boil:"reply" json:"reply" toml:"reply" yaml:"reply"`
	KolID     string         `boil:"kol_id" json:"kol_id" toml:"kol_id" yaml:"kol_id"`
	KolName   string         `boil:"kol_name" json:"kol_name" toml:"kol_name" yaml:"kol_name"`
	Status    EmailLogStatus `boil:"status" json:"status" toml:"status" yaml:"status"`
	Momo      string         `boil:"momo" json:"momo" toml:"momo" yaml:"momo"`
	CreatedAt time.Time      `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time      `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	SendedAt  null.Time      `boil:"sended_at" json:"sended_at,omitempty" toml:"sended_at" yaml:"sended_at,omitempty"`

	R *emailLogR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L emailLogL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EmailLogColumns = struct {
	ID        string
	JobID     string
	ProductID string
	SenderID  string
	Email     string
	MessageID string
	Reply     string
	KolID     string
	KolName   string
	Status    string
	Momo      string
	CreatedAt string
	UpdatedAt string
	SendedAt  string
}{
	ID:        "id",
	JobID:     "job_id",
	ProductID: "product_id",
	SenderID:  "sender_id",
	Email:     "email",
	MessageID: "message_id",
	Reply:     "reply",
	KolID:     "kol_id",
	KolName:   "kol_name",
	Status:    "status",
	Momo:      "momo",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	SendedAt:  "sended_at",
}

var EmailLogTableColumns = struct {
	ID        string
	JobID     string
	ProductID string
	SenderID  string
	Email     string
	MessageID string
	Reply     string
	KolID     string
	KolName   string
	Status    string
	Momo      string
	CreatedAt string
	UpdatedAt string
	SendedAt  string
}{
	ID:        "email_log.id",
	JobID:     "email_log.job_id",
	ProductID: "email_log.product_id",
	SenderID:  "email_log.sender_id",
	Email:     "email_log.email",
	MessageID: "email_log.message_id",
	Reply:     "email_log.reply",
	KolID:     "email_log.kol_id",
	KolName:   "email_log.kol_name",
	Status:    "email_log.status",
	Momo:      "email_log.momo",
	CreatedAt: "email_log.created_at",
	UpdatedAt: "email_log.updated_at",
	SendedAt:  "email_log.sended_at",
}

// Generated where

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

type whereHelperEmailLogStatus struct{ field string }

func (w whereHelperEmailLogStatus) EQ(x EmailLogStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperEmailLogStatus) NEQ(x EmailLogStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperEmailLogStatus) LT(x EmailLogStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperEmailLogStatus) LTE(x EmailLogStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperEmailLogStatus) GT(x EmailLogStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperEmailLogStatus) GTE(x EmailLogStatus) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperEmailLogStatus) IN(slice []EmailLogStatus) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperEmailLogStatus) NIN(slice []EmailLogStatus) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var EmailLogWhere = struct {
	ID        whereHelperint64
	JobID     whereHelperint64
	ProductID whereHelperstring
	SenderID  whereHelperstring
	Email     whereHelperstring
	MessageID whereHelperstring
	Reply     whereHelperbool
	KolID     whereHelperstring
	KolName   whereHelperstring
	Status    whereHelperEmailLogStatus
	Momo      whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
	SendedAt  whereHelpernull_Time
}{
	ID:        whereHelperint64{field: "\"email_log\".\"id\""},
	JobID:     whereHelperint64{field: "\"email_log\".\"job_id\""},
	ProductID: whereHelperstring{field: "\"email_log\".\"product_id\""},
	SenderID:  whereHelperstring{field: "\"email_log\".\"sender_id\""},
	Email:     whereHelperstring{field: "\"email_log\".\"email\""},
	MessageID: whereHelperstring{field: "\"email_log\".\"message_id\""},
	Reply:     whereHelperbool{field: "\"email_log\".\"reply\""},
	KolID:     whereHelperstring{field: "\"email_log\".\"kol_id\""},
	KolName:   whereHelperstring{field: "\"email_log\".\"kol_name\""},
	Status:    whereHelperEmailLogStatus{field: "\"email_log\".\"status\""},
	Momo:      whereHelperstring{field: "\"email_log\".\"momo\""},
	CreatedAt: whereHelpertime_Time{field: "\"email_log\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"email_log\".\"updated_at\""},
	SendedAt:  whereHelpernull_Time{field: "\"email_log\".\"sended_at\""},
}

// EmailLogRels is where relationship names are stored.
var EmailLogRels = struct {
}{}

// emailLogR is where relationships are stored.
type emailLogR struct {
}

// NewStruct creates a new relationship struct
func (*emailLogR) NewStruct() *emailLogR {
	return &emailLogR{}
}

// emailLogL is where Load methods for each relationship are stored.
type emailLogL struct{}

var (
	emailLogAllColumns            = []string{"id", "job_id", "product_id", "sender_id", "email", "message_id", "reply", "kol_id", "kol_name", "status", "momo", "created_at", "updated_at", "sended_at"}
	emailLogColumnsWithoutDefault = []string{"job_id", "product_id", "sender_id", "email", "message_id", "kol_id", "kol_name", "status", "momo"}
	emailLogColumnsWithDefault    = []string{"id", "reply", "created_at", "updated_at", "sended_at"}
	emailLogPrimaryKeyColumns     = []string{"id"}
	emailLogGeneratedColumns      = []string{}
)

type (
	// EmailLogSlice is an alias for a slice of pointers to EmailLog.
	// This should almost always be used instead of []EmailLog.
	EmailLogSlice []*EmailLog
	// EmailLogHook is the signature for custom EmailLog hook methods
	EmailLogHook func(context.Context, boil.ContextExecutor, *EmailLog) error

	emailLogQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	emailLogType                 = reflect.TypeOf(&EmailLog{})
	emailLogMapping              = queries.MakeStructMapping(emailLogType)
	emailLogPrimaryKeyMapping, _ = queries.BindMapping(emailLogType, emailLogMapping, emailLogPrimaryKeyColumns)
	emailLogInsertCacheMut       sync.RWMutex
	emailLogInsertCache          = make(map[string]insertCache)
	emailLogUpdateCacheMut       sync.RWMutex
	emailLogUpdateCache          = make(map[string]updateCache)
	emailLogUpsertCacheMut       sync.RWMutex
	emailLogUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var emailLogAfterSelectMu sync.Mutex
var emailLogAfterSelectHooks []EmailLogHook

var emailLogBeforeInsertMu sync.Mutex
var emailLogBeforeInsertHooks []EmailLogHook
var emailLogAfterInsertMu sync.Mutex
var emailLogAfterInsertHooks []EmailLogHook

var emailLogBeforeUpdateMu sync.Mutex
var emailLogBeforeUpdateHooks []EmailLogHook
var emailLogAfterUpdateMu sync.Mutex
var emailLogAfterUpdateHooks []EmailLogHook

var emailLogBeforeDeleteMu sync.Mutex
var emailLogBeforeDeleteHooks []EmailLogHook
var emailLogAfterDeleteMu sync.Mutex
var emailLogAfterDeleteHooks []EmailLogHook

var emailLogBeforeUpsertMu sync.Mutex
var emailLogBeforeUpsertHooks []EmailLogHook
var emailLogAfterUpsertMu sync.Mutex
var emailLogAfterUpsertHooks []EmailLogHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EmailLog) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailLogAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EmailLog) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailLogBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EmailLog) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailLogAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EmailLog) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailLogBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EmailLog) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailLogAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EmailLog) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailLogBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EmailLog) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailLogAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EmailLog) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailLogBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EmailLog) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailLogAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEmailLogHook registers your hook function for all future operations.
func AddEmailLogHook(hookPoint boil.HookPoint, emailLogHook EmailLogHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		emailLogAfterSelectMu.Lock()
		emailLogAfterSelectHooks = append(emailLogAfterSelectHooks, emailLogHook)
		emailLogAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		emailLogBeforeInsertMu.Lock()
		emailLogBeforeInsertHooks = append(emailLogBeforeInsertHooks, emailLogHook)
		emailLogBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		emailLogAfterInsertMu.Lock()
		emailLogAfterInsertHooks = append(emailLogAfterInsertHooks, emailLogHook)
		emailLogAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		emailLogBeforeUpdateMu.Lock()
		emailLogBeforeUpdateHooks = append(emailLogBeforeUpdateHooks, emailLogHook)
		emailLogBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		emailLogAfterUpdateMu.Lock()
		emailLogAfterUpdateHooks = append(emailLogAfterUpdateHooks, emailLogHook)
		emailLogAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		emailLogBeforeDeleteMu.Lock()
		emailLogBeforeDeleteHooks = append(emailLogBeforeDeleteHooks, emailLogHook)
		emailLogBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		emailLogAfterDeleteMu.Lock()
		emailLogAfterDeleteHooks = append(emailLogAfterDeleteHooks, emailLogHook)
		emailLogAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		emailLogBeforeUpsertMu.Lock()
		emailLogBeforeUpsertHooks = append(emailLogBeforeUpsertHooks, emailLogHook)
		emailLogBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		emailLogAfterUpsertMu.Lock()
		emailLogAfterUpsertHooks = append(emailLogAfterUpsertHooks, emailLogHook)
		emailLogAfterUpsertMu.Unlock()
	}
}

// One returns a single emailLog record from the query.
func (q emailLogQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EmailLog, error) {
	o := &EmailLog{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to execute a one query for email_log")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EmailLog records from the query.
func (q emailLogQuery) All(ctx context.Context, exec boil.ContextExecutor) (EmailLogSlice, error) {
	var o []*EmailLog

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to EmailLog slice")
	}

	if len(emailLogAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EmailLog records in the query.
func (q emailLogQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count email_log rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q emailLogQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if email_log exists")
	}

	return count > 0, nil
}

// EmailLogs retrieves all the records using an executor.
func EmailLogs(mods ...qm.QueryMod) emailLogQuery {
	mods = append(mods, qm.From("\"email_log\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"email_log\".*"})
	}

	return emailLogQuery{q}
}

// FindEmailLog retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEmailLog(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*EmailLog, error) {
	emailLogObj := &EmailLog{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"email_log\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, emailLogObj)
	if err != nil {
		return nil, errors.Wrap(err, "model: unable to select from email_log")
	}

	if err = emailLogObj.doAfterSelectHooks(ctx, exec); err != nil {
		return emailLogObj, err
	}

	return emailLogObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EmailLog) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no email_log provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailLogColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	emailLogInsertCacheMut.RLock()
	cache, cached := emailLogInsertCache[key]
	emailLogInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			emailLogAllColumns,
			emailLogColumnsWithDefault,
			emailLogColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(emailLogType, emailLogMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(emailLogType, emailLogMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"email_log\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"email_log\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into email_log")
	}

	if !cached {
		emailLogInsertCacheMut.Lock()
		emailLogInsertCache[key] = cache
		emailLogInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EmailLog.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EmailLog) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	emailLogUpdateCacheMut.RLock()
	cache, cached := emailLogUpdateCache[key]
	emailLogUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			emailLogAllColumns,
			emailLogPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("model: unable to update email_log, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"email_log\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, emailLogPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(emailLogType, emailLogMapping, append(wl, emailLogPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update email_log row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by update for email_log")
	}

	if !cached {
		emailLogUpdateCacheMut.Lock()
		emailLogUpdateCache[key] = cache
		emailLogUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q emailLogQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all for email_log")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected for email_log")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EmailLogSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"email_log\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, emailLogPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all in emailLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected all in update all emailLog")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EmailLog) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("model: no email_log provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailLogColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	emailLogUpsertCacheMut.RLock()
	cache, cached := emailLogUpsertCache[key]
	emailLogUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			emailLogAllColumns,
			emailLogColumnsWithDefault,
			emailLogColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			emailLogAllColumns,
			emailLogPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("model: unable to upsert email_log, could not build update column list")
		}

		ret := strmangle.SetComplement(emailLogAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(emailLogPrimaryKeyColumns) == 0 {
				return errors.New("model: unable to upsert email_log, could not build conflict column list")
			}

			conflict = make([]string, len(emailLogPrimaryKeyColumns))
			copy(conflict, emailLogPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"email_log\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(emailLogType, emailLogMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(emailLogType, emailLogMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "model: unable to upsert email_log")
	}

	if !cached {
		emailLogUpsertCacheMut.Lock()
		emailLogUpsertCache[key] = cache
		emailLogUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EmailLog record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EmailLog) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no EmailLog provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), emailLogPrimaryKeyMapping)
	sql := "DELETE FROM \"email_log\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete from email_log")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by delete for email_log")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q emailLogQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("model: no emailLogQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from email_log")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for email_log")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EmailLogSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(emailLogBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"email_log\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailLogPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from emailLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for email_log")
	}

	if len(emailLogAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EmailLog) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEmailLog(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EmailLogSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EmailLogSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"email_log\".* FROM \"email_log\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailLogPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in EmailLogSlice")
	}

	*o = slice

	return nil
}

// EmailLogExists checks if the EmailLog row exists.
func EmailLogExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"email_log\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if email_log exists")
	}

	return exists, nil
}

// Exists checks if the EmailLog row exists.
func (o *EmailLog) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EmailLogExists(ctx, exec, o.ID)
}
